// ============================================================
// ReelMind — Mock Data
// ============================================================

import {
  ProcessedReel, Notification, AnalyticsData, ChatMessage,
  PipelineStep, PriceComparison,
} from './types';

// --- Mock Processed Reels ---
export const MOCK_REELS: ProcessedReel[] = [
  {
    id: 'reel-001',
    originalUrl: 'https://www.instagram.com/reel/ABC123',
    thumbnailUrl: '/thumbnails/food-01.jpg',
    title: 'Hidden Gem Café in Kochi',
    category: 'Food',
    summary: 'A cozy café in Fort Kochi serving authentic Kerala cuisine with a modern twist. Known for their fish curry rice bowl and filter coffee. Located near the Chinese fishing nets area.',
    tags: ['café', 'kochi', 'kerala cuisine', 'filter coffee', 'hidden gem'],
    language: 'English',
    transcript: 'Hey guys, today I found this amazing café in Fort Kochi...',
    ocrText: 'Open 8AM - 10PM | ₹200-500 per person',
    caption: 'Best café in Kochi! 🔥 #KochiFood #HiddenGem',
    entities: {
      dates: [],
      locations: ['Fort Kochi, Kerala'],
      prices: ['₹200-500'],
      links: [],
      phoneNumbers: ['+91 9876543210'],
      deadlines: [],
    },
    categoryData: {
      type: 'Food',
      data: {
        restaurantName: 'The Wharf Café',
        location: 'Fort Kochi, Kerala, India',
        cuisine: 'Kerala Fusion',
        priceRange: '₹200 - ₹500',
        openingHours: '8:00 AM - 10:00 PM',
        popularItems: ['Fish Curry Rice Bowl', 'Kerala Filter Coffee', 'Banana Fritters', 'Prawn Malabar'],
        coordinates: { lat: 9.9637, lng: 76.2375 },
        googleMapsLink: 'https://maps.google.com/?q=9.9637,76.2375',
        rating: 4.6,
      },
    },
    isFavorite: true,
    isArchived: false,
    createdAt: '2026-07-28T10:30:00Z',
    processedAt: '2026-07-28T10:31:15Z',
    reminderDate: '2026-08-02T09:00:00Z',
    reminderType: 'food_nearby',
  },
  {
    id: 'reel-002',
    originalUrl: 'https://www.instagram.com/reel/DEF456',
    thumbnailUrl: '/thumbnails/event-01.jpg',
    title: 'AI Hackathon at IIT Madras',
    category: 'Events',
    summary: 'A 48-hour AI hackathon organized by IIT Madras with prizes worth ₹5 lakhs. Open to all college students. Registration closes August 10th.',
    tags: ['hackathon', 'AI', 'IIT Madras', 'coding', 'prizes'],
    language: 'English',
    transcript: 'Attention all coders! IIT Madras is hosting a massive AI hackathon...',
    ocrText: 'Register at hackathon.iitm.ac.in | Deadline: Aug 10',
    caption: 'Don\'t miss this! 🚀 #AIHackathon #IITMadras',
    entities: {
      dates: ['August 15-17, 2026'],
      locations: ['IIT Madras, Chennai'],
      prices: ['Free Entry'],
      links: ['hackathon.iitm.ac.in'],
      phoneNumbers: [],
      deadlines: ['August 10, 2026'],
    },
    categoryData: {
      type: 'Events',
      data: {
        eventName: 'AI Hackathon 2026',
        date: 'August 15-17, 2026',
        time: '9:00 AM IST',
        venue: 'IIT Madras Campus, Chennai',
        registrationDeadline: 'August 10, 2026',
        fee: 'Free',
        registrationLink: 'https://hackathon.iitm.ac.in',
        organizer: 'IIT Madras AI Club',
        eligibility: 'All college students',
      },
    },
    isFavorite: false,
    isArchived: false,
    createdAt: '2026-07-25T14:00:00Z',
    processedAt: '2026-07-25T14:01:30Z',
    reminderDate: '2026-08-09T09:00:00Z',
    reminderType: 'event_reminder',
  },
  {
    id: 'reel-003',
    originalUrl: 'https://www.instagram.com/reel/GHI789',
    thumbnailUrl: '/thumbnails/scholarship-01.jpg',
    title: 'Fully Funded Masters in Germany',
    category: 'Scholarships',
    summary: 'DAAD Scholarship for Masters programs in Germany. Fully funded including tuition, living allowance, and travel costs. Open to students from developing countries.',
    tags: ['scholarship', 'Germany', 'DAAD', 'masters', 'fully funded'],
    language: 'English',
    transcript: 'If you want to study in Germany for free, listen carefully...',
    ocrText: 'Apply at daad.de/en | Deadline: October 15, 2026',
    caption: 'Life-changing opportunity! 🇩🇪 #DAAD #Scholarship',
    entities: {
      dates: ['October 15, 2026'],
      locations: ['Germany'],
      prices: [],
      links: ['daad.de/en'],
      phoneNumbers: [],
      deadlines: ['October 15, 2026'],
    },
    categoryData: {
      type: 'Scholarships',
      data: {
        name: 'DAAD Development-Related Postgraduate Courses',
        deadline: 'October 15, 2026',
        country: 'Germany',
        funding: 'Full funding: €934/month + tuition + travel + insurance',
        eligibility: 'Bachelor\'s degree holders from developing countries with 2+ years work experience',
        officialWebsite: 'https://www.daad.de/en',
        documentsRequired: ['Bachelor\'s transcripts', 'CV', 'Motivation letter', 'Reference letters (2)', 'Language certificate', 'Work experience proof'],
      },
    },
    isFavorite: true,
    isArchived: false,
    createdAt: '2026-07-20T08:00:00Z',
    processedAt: '2026-07-20T08:02:00Z',
    reminderDate: '2026-10-12T09:00:00Z',
    reminderType: 'scholarship_deadline',
  },
  {
    id: 'reel-004',
    originalUrl: 'https://www.instagram.com/reel/JKL012',
    thumbnailUrl: '/thumbnails/job-01.jpg',
    title: 'Google Hiring SDE Interns',
    category: 'Jobs',
    summary: 'Google is hiring Software Development Engineer interns for Summer 2027. Competitive stipend, Bangalore location. Apply through careers.google.com.',
    tags: ['Google', 'internship', 'SDE', 'software', 'Bangalore'],
    language: 'English',
    transcript: 'Big news! Google just opened applications for SDE interns...',
    ocrText: 'Apply at careers.google.com | Stipend: ₹1.2L/month',
    caption: 'Dream internship alert! 🌟 #Google #Internship',
    entities: {
      dates: [],
      locations: ['Bangalore, India'],
      prices: ['₹1.2L/month'],
      links: ['careers.google.com'],
      phoneNumbers: [],
      deadlines: ['September 30, 2026'],
    },
    categoryData: {
      type: 'Jobs',
      data: {
        company: 'Google',
        role: 'Software Development Engineer Intern',
        salary: '₹1,20,000/month + benefits',
        location: 'Bangalore, India',
        experience: '0-1 years (College students)',
        applyLink: 'https://careers.google.com',
        deadline: 'September 30, 2026',
        skills: ['DSA', 'Python/Java/C++', 'System Design basics', 'Problem Solving'],
      },
    },
    isFavorite: true,
    isArchived: false,
    createdAt: '2026-07-22T16:00:00Z',
    processedAt: '2026-07-22T16:01:45Z',
    reminderDate: '2026-09-25T09:00:00Z',
    reminderType: 'job_deadline',
  },
  {
    id: 'reel-005',
    originalUrl: 'https://www.instagram.com/reel/MNO345',
    thumbnailUrl: '/thumbnails/recipe-01.jpg',
    title: 'Easy Butter Chicken Recipe',
    category: 'Recipes',
    summary: 'A quick and easy butter chicken recipe that takes only 30 minutes. Creamy, rich, and restaurant-quality at home.',
    tags: ['butter chicken', 'recipe', 'Indian food', 'quick recipe', 'dinner'],
    language: 'Hindi',
    transcript: 'Aaj main aapko sikhaunga butter chicken banane ka sabse asaan tarika...',
    ocrText: '',
    caption: 'Restaurant jaisa butter chicken ghar pe! 🍗 #ButterChicken #Recipe',
    entities: {
      dates: [],
      locations: [],
      prices: [],
      links: [],
      phoneNumbers: [],
      deadlines: [],
    },
    categoryData: {
      type: 'Recipes',
      data: {
        dishName: 'Butter Chicken',
        ingredients: [
          { name: 'Chicken', measurement: '500g boneless' },
          { name: 'Butter', measurement: '3 tbsp' },
          { name: 'Tomato puree', measurement: '1 cup' },
          { name: 'Heavy cream', measurement: '½ cup' },
          { name: 'Yogurt', measurement: '½ cup' },
          { name: 'Ginger-garlic paste', measurement: '2 tbsp' },
          { name: 'Garam masala', measurement: '1 tsp' },
          { name: 'Red chilli powder', measurement: '1 tsp' },
          { name: 'Kasuri methi', measurement: '1 tbsp' },
        ],
        steps: [
          'Marinate chicken in yogurt and spices for 30 mins',
          'Cook chicken in butter until golden',
          'Add ginger-garlic paste and sauté',
          'Add tomato puree and cook for 10 mins',
          'Add cream and simmer for 5 mins',
          'Finish with kasuri methi and butter',
        ],
        prepTime: '30 minutes',
        cookTime: '25 minutes',
        servings: 4,
        difficulty: 'Easy',
      },
    },
    isFavorite: false,
    isArchived: false,
    createdAt: '2026-07-18T12:00:00Z',
    processedAt: '2026-07-18T12:01:20Z',
  },
  {
    id: 'reel-006',
    originalUrl: 'https://www.instagram.com/reel/PQR678',
    thumbnailUrl: '/thumbnails/shopping-01.jpg',
    title: 'Sony WH-1000XM5 Review',
    category: 'Shopping',
    summary: 'Detailed review of Sony WH-1000XM5 wireless headphones. Best-in-class noise cancellation, 30-hour battery, and exceptional sound quality.',
    tags: ['Sony', 'headphones', 'noise cancellation', 'review', 'tech'],
    language: 'English',
    transcript: 'These are hands down the best noise cancelling headphones you can buy...',
    ocrText: 'MRP: ₹29,990 | Available on Amazon & Flipkart',
    caption: 'Best headphones of 2026? 🎧 #Sony #XM5 #Review',
    entities: {
      dates: [],
      locations: [],
      prices: ['₹29,990'],
      links: [],
      phoneNumbers: [],
      deadlines: [],
    },
    categoryData: {
      type: 'Shopping',
      data: {
        brand: 'Sony',
        model: 'WH-1000XM5',
        features: ['Industry-leading ANC', '30-hour battery', 'Multipoint connection', 'Speak-to-Chat', 'LDAC support'],
        specifications: {
          'Driver Size': '30mm',
          'Frequency Response': '4Hz-40kHz',
          'Battery Life': '30 hours',
          'Weight': '250g',
          'Connectivity': 'Bluetooth 5.2',
          'Noise Cancellation': 'Adaptive ANC',
        },
        mentionedPrice: '₹29,990',
      },
    },
    priceComparison: {
      productName: 'Sony WH-1000XM5',
      mentionedPrice: 29990,
      currency: '₹',
      items: [
        { store: 'Amazon', storeLogo: '/stores/amazon.svg', price: 24990, currency: '₹', url: 'https://amazon.in', inStock: true, isOfficial: false },
        { store: 'Flipkart', storeLogo: '/stores/flipkart.svg', price: 25490, currency: '₹', url: 'https://flipkart.com', inStock: true, isOfficial: false },
        { store: 'Sony Store', storeLogo: '/stores/sony.svg', price: 29990, currency: '₹', url: 'https://store.sony.co.in', inStock: true, isOfficial: true },
        { store: 'Croma', storeLogo: '/stores/croma.svg', price: 26990, currency: '₹', url: 'https://croma.com', inStock: true, isOfficial: false },
      ],
      cheapestStore: 'Amazon',
      estimatedSavings: 5000,
      alternatives: [
        { name: 'Bose QC Ultra', price: 26900, url: 'https://amazon.in' },
        { name: 'Apple AirPods Max', price: 59900, url: 'https://amazon.in' },
        { name: 'Sennheiser Momentum 4', price: 24990, url: 'https://amazon.in' },
      ],
    },
    isFavorite: false,
    isArchived: false,
    createdAt: '2026-07-15T20:00:00Z',
    processedAt: '2026-07-15T20:02:00Z',
  },
  {
    id: 'reel-007',
    originalUrl: 'https://www.instagram.com/reel/STU901',
    thumbnailUrl: '/thumbnails/travel-01.jpg',
    title: 'Manali on a Budget',
    category: 'Travel',
    summary: 'Complete budget travel guide to Manali. Covers transport, stays, food, and activities under ₹8000 for 3 days.',
    tags: ['Manali', 'budget travel', 'Himachal', 'mountains', 'backpacking'],
    language: 'Hindi',
    transcript: 'Manali trip sirf 8000 mein kaise karein, main bataunga...',
    ocrText: 'Budget: ₹8000 for 3 days',
    caption: 'Manali trip under ₹8K! 🏔️ #Manali #BudgetTravel',
    entities: {
      dates: [],
      locations: ['Manali, Himachal Pradesh'],
      prices: ['₹8000'],
      links: [],
      phoneNumbers: [],
      deadlines: [],
    },
    categoryData: {
      type: 'Travel',
      data: {
        destination: 'Manali, Himachal Pradesh',
        bestTime: 'March - June, October - December',
        budget: '₹8,000 for 3 days',
        highlights: ['Solang Valley', 'Old Manali', 'Hadimba Temple', 'Jogini Waterfall', 'Rohtang Pass'],
        tips: ['Take HRTC bus from Delhi for ₹800', 'Stay in Old Manali hostels ₹300/night', 'Eat at local dhabas', 'Rent a scooter for ₹500/day'],
        coordinates: { lat: 32.2396, lng: 77.1887 },
      },
    },
    isFavorite: false,
    isArchived: false,
    createdAt: '2026-07-12T09:00:00Z',
    processedAt: '2026-07-12T09:01:30Z',
  },
  {
    id: 'reel-008',
    originalUrl: 'https://www.instagram.com/reel/VWX234',
    thumbnailUrl: '/thumbnails/course-01.jpg',
    title: 'Free Machine Learning Course by Stanford',
    category: 'Courses',
    summary: 'Stanford\'s CS229 Machine Learning course is now available for free on Coursera. Taught by Andrew Ng. Includes certificate.',
    tags: ['ML', 'Stanford', 'free course', 'Andrew Ng', 'Coursera'],
    language: 'English',
    transcript: 'The most famous machine learning course is now completely free...',
    ocrText: 'coursera.org/learn/machine-learning | Free with certificate',
    caption: 'Best ML course, now FREE! 🎓 #MachineLearning #Stanford',
    entities: {
      dates: [],
      locations: [],
      prices: ['Free'],
      links: ['coursera.org/learn/machine-learning'],
      phoneNumbers: [],
      deadlines: [],
    },
    isFavorite: true,
    isArchived: false,
    createdAt: '2026-07-10T11:00:00Z',
    processedAt: '2026-07-10T11:01:00Z',
  },
  {
    id: 'reel-009',
    originalUrl: 'https://www.instagram.com/reel/YZA567',
    thumbnailUrl: '/thumbnails/fitness-01.jpg',
    title: '30-Day Home Workout Plan',
    category: 'Fitness',
    summary: 'Complete 30-day workout plan requiring no equipment. Targets full body with progressive overload. 20 minutes per day.',
    tags: ['workout', 'home exercise', 'no equipment', '30-day challenge', 'fitness'],
    language: 'English',
    transcript: 'No gym? No problem. Here\'s a 30-day plan that actually works...',
    ocrText: 'Day 1-10: Foundation | Day 11-20: Build | Day 21-30: Peak',
    caption: 'Transform in 30 days! 💪 #HomeWorkout #FitnessChallenge',
    entities: {
      dates: [],
      locations: [],
      prices: [],
      links: [],
      phoneNumbers: [],
      deadlines: [],
    },
    isFavorite: false,
    isArchived: false,
    createdAt: '2026-07-08T06:00:00Z',
    processedAt: '2026-07-08T06:01:15Z',
  },
  {
    id: 'reel-010',
    originalUrl: 'https://www.instagram.com/reel/BCD890',
    thumbnailUrl: '/thumbnails/movie-01.jpg',
    title: 'Upcoming Marvel Movie Leaked Details',
    category: 'Movies',
    summary: 'Avengers: Secret Wars confirmed for December 2026. Robert Downey Jr. returns. Multiverse saga conclusion.',
    tags: ['Marvel', 'Avengers', 'Secret Wars', 'MCU', 'movies'],
    language: 'English',
    transcript: 'Marvel just dropped a bombshell announcement about Secret Wars...',
    ocrText: 'Release: December 25, 2026',
    caption: 'MCU fans, this is HUGE! 🎬 #Marvel #SecretWars',
    entities: {
      dates: ['December 25, 2026'],
      locations: [],
      prices: [],
      links: [],
      phoneNumbers: [],
      deadlines: [],
    },
    isFavorite: false,
    isArchived: false,
    createdAt: '2026-07-05T18:00:00Z',
    processedAt: '2026-07-05T18:01:00Z',
    reminderDate: '2026-12-24T09:00:00Z',
    reminderType: 'movie_release',
  },
  {
    id: 'reel-011',
    originalUrl: 'https://www.instagram.com/reel/EFG123',
    thumbnailUrl: '/thumbnails/beauty-01.jpg',
    title: 'Korean Glass Skin Routine',
    category: 'Beauty',
    summary: '10-step Korean skincare routine for achieving glass skin. Affordable products available in India.',
    tags: ['skincare', 'Korean beauty', 'glass skin', 'routine', 'K-beauty'],
    language: 'English',
    transcript: 'Let me share my Korean glass skin routine using only affordable products...',
    ocrText: 'Total cost: Under ₹3000',
    caption: 'Glass skin in 2 weeks! ✨ #KBeauty #GlassSkin',
    entities: {
      dates: [],
      locations: [],
      prices: ['₹3000'],
      links: [],
      phoneNumbers: [],
      deadlines: [],
    },
    isFavorite: false,
    isArchived: false,
    createdAt: '2026-07-03T15:00:00Z',
    processedAt: '2026-07-03T15:01:30Z',
  },
  {
    id: 'reel-012',
    originalUrl: 'https://www.instagram.com/reel/HIJ456',
    thumbnailUrl: '/thumbnails/finance-01.jpg',
    title: 'Invest ₹500/month Strategy',
    category: 'Finance',
    summary: 'SIP investment strategy starting with just ₹500/month. Covers mutual funds, index funds, and compound interest magic.',
    tags: ['investment', 'SIP', 'mutual funds', 'personal finance', 'money'],
    language: 'Hindi',
    transcript: 'Sirf 500 rupay mahine se crorepati kaise bane...',
    ocrText: '₹500/month → ₹1 Crore in 30 years',
    caption: 'Start investing TODAY! 💰 #SIP #Investment',
    entities: {
      dates: [],
      locations: [],
      prices: ['₹500/month'],
      links: [],
      phoneNumbers: [],
      deadlines: [],
    },
    isFavorite: true,
    isArchived: false,
    createdAt: '2026-07-01T10:00:00Z',
    processedAt: '2026-07-01T10:01:00Z',
  },
];

// --- Mock Notifications ---
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    type: 'food_nearby',
    title: 'Restaurant Nearby!',
    message: 'The Wharf Café from your saved reel is only 500 meters away. Great time for a filter coffee!',
    reelId: 'reel-001',
    isRead: false,
    createdAt: '2026-08-01T07:00:00Z',
    icon: '🍔',
  },
  {
    id: 'notif-002',
    type: 'event_reminder',
    title: 'Registration Closing Soon',
    message: 'AI Hackathon at IIT Madras — registration closes in 9 days. Don\'t miss out!',
    reelId: 'reel-002',
    isRead: false,
    createdAt: '2026-08-01T06:00:00Z',
    actionUrl: 'https://hackathon.iitm.ac.in',
    icon: '🎉',
  },
  {
    id: 'notif-003',
    type: 'scholarship_deadline',
    title: 'Scholarship Deadline Alert',
    message: 'DAAD Scholarship applications close in 75 days. Start preparing your documents!',
    reelId: 'reel-003',
    isRead: true,
    createdAt: '2026-07-30T09:00:00Z',
    icon: '🎓',
  },
  {
    id: 'notif-004',
    type: 'discount_expiry',
    title: 'Price Drop Alert!',
    message: 'Sony WH-1000XM5 is now ₹24,990 on Amazon — ₹5,000 off! Deal ends tonight.',
    reelId: 'reel-006',
    isRead: false,
    createdAt: '2026-08-01T05:00:00Z',
    actionUrl: 'https://amazon.in',
    icon: '🛍️',
  },
  {
    id: 'notif-005',
    type: 'movie_release',
    title: 'Movie Releasing Soon!',
    message: 'Avengers: Secret Wars releases December 25th. Mark your calendar!',
    reelId: 'reel-010',
    isRead: true,
    createdAt: '2026-07-29T12:00:00Z',
    icon: '🎬',
  },
  {
    id: 'notif-006',
    type: 'job_deadline',
    title: 'Application Deadline',
    message: 'Google SDE Intern applications close September 30th. Start preparing!',
    reelId: 'reel-004',
    isRead: false,
    createdAt: '2026-07-28T09:00:00Z',
    icon: '💼',
  },
];

// --- Mock Analytics ---
export const MOCK_ANALYTICS: AnalyticsData = {
  totalReels: 12,
  upcomingReminders: 6,
  nearbyPlaces: 3,
  savedMoney: 5000,
  categoryBreakdown: [
    { category: 'Food', count: 3 },
    { category: 'Events', count: 2 },
    { category: 'Scholarships', count: 1 },
    { category: 'Jobs', count: 2 },
    { category: 'Recipes', count: 1 },
    { category: 'Shopping', count: 2 },
    { category: 'Travel', count: 2 },
    { category: 'Courses', count: 3 },
    { category: 'Fitness', count: 1 },
    { category: 'Movies', count: 1 },
    { category: 'Beauty', count: 2 },
    { category: 'Finance', count: 1 },
    { category: 'Technology', count: 1 },
  ],
  monthlyActivity: [
    { month: 'Feb', count: 3 },
    { month: 'Mar', count: 5 },
    { month: 'Apr', count: 8 },
    { month: 'May', count: 12 },
    { month: 'Jun', count: 7 },
    { month: 'Jul', count: 15 },
    { month: 'Aug', count: 4 },
  ],
  moneySavedByMonth: [
    { month: 'Feb', amount: 200 },
    { month: 'Mar', amount: 800 },
    { month: 'Apr', amount: 1500 },
    { month: 'May', amount: 2200 },
    { month: 'Jun', amount: 3400 },
    { month: 'Jul', amount: 5000 },
    { month: 'Aug', amount: 5000 },
  ],
  upcomingDeadlines: [
    { title: 'AI Hackathon Registration', date: '2026-08-10', category: 'Events', reelId: 'reel-002' },
    { title: 'Google SDE Intern Apply', date: '2026-09-30', category: 'Jobs', reelId: 'reel-004' },
    { title: 'DAAD Scholarship', date: '2026-10-15', category: 'Scholarships', reelId: 'reel-003' },
  ],
};

// --- Mock Chat History ---
export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'chat-001',
    role: 'assistant',
    content: 'Hey! 👋 I\'m your ReelMind AI assistant. I can help you find information from your saved reels, remind you about deadlines, and answer questions about your knowledge base. What would you like to know?',
    timestamp: '2026-08-01T07:00:00Z',
  },
];

// --- Mock Chat Responses ---
export const MOCK_CHAT_RESPONSES: Record<string, { content: string; reelRefs?: { id: string; title: string; thumbnail: string }[] }> = {
  'default': {
    content: 'I found some interesting information in your saved reels. Let me help you with that!',
  },
  'scholarship': {
    content: 'You have **1 scholarship** saved with an upcoming deadline:\n\n📌 **DAAD Scholarship** — Deadline: October 15, 2026\n- Fully funded Masters in Germany\n- Includes tuition, ₹934/month living allowance, travel costs\n- You still have **75 days** to apply!\n\nWould you like me to set a reminder for the document preparation?',
    reelRefs: [{ id: 'reel-003', title: 'Fully Funded Masters in Germany', thumbnail: '/thumbnails/scholarship-01.jpg' }],
  },
  'food': {
    content: 'Here are your saved food reels:\n\n🍔 **The Wharf Café** — Fort Kochi, Kerala\n- Kerala Fusion cuisine, ₹200-500 per person\n- Known for Fish Curry Rice Bowl & Filter Coffee\n- Rating: 4.6⭐\n\nWant me to show you directions?',
    reelRefs: [{ id: 'reel-001', title: 'Hidden Gem Café in Kochi', thumbnail: '/thumbnails/food-01.jpg' }],
  },
  'hackathon': {
    content: 'I found **1 hackathon** in your saved reels:\n\n🎉 **AI Hackathon 2026** at IIT Madras\n- Dates: August 15-17, 2026\n- Registration deadline: **August 10** (9 days left!)\n- Free entry, prizes worth ₹5 lakhs\n- Open to all college students\n\n⚠️ Registration closing soon! Should I open the registration link?',
    reelRefs: [{ id: 'reel-002', title: 'AI Hackathon at IIT Madras', thumbnail: '/thumbnails/event-01.jpg' }],
  },
  'python': {
    content: 'While none of your reels specifically mention Python, the **Google SDE Intern** position lists **Python** as a required skill, and the **Stanford ML Course** uses Python extensively.\n\nWould you like me to search for Python-specific reels?',
    reelRefs: [
      { id: 'reel-004', title: 'Google Hiring SDE Interns', thumbnail: '/thumbnails/job-01.jpg' },
      { id: 'reel-008', title: 'Free Machine Learning Course by Stanford', thumbnail: '/thumbnails/course-01.jpg' },
    ],
  },
  'headphones': {
    content: 'Great question! Here\'s what I found:\n\n🎧 **Sony WH-1000XM5** — Your saved review\n- Best Price: **₹24,990** on Amazon (₹5,000 off!)\n- Features: Industry-leading ANC, 30hr battery\n\n💡 I also found cheaper alternatives:\n- Sennheiser Momentum 4: ₹24,990\n- Bose QC Ultra: ₹26,900\n\nWant me to compare them in detail?',
    reelRefs: [{ id: 'reel-006', title: 'Sony WH-1000XM5 Review', thumbnail: '/thumbnails/shopping-01.jpg' }],
  },
};

// --- Processing Pipeline Steps ---
export const PIPELINE_STEPS: PipelineStep[] = [
  { id: 'downloading', label: 'Downloading Reel', description: 'Fetching reel content from Instagram', status: 'pending', progress: 0 },
  { id: 'extracting_audio', label: 'Extracting Audio', description: 'Separating audio track from video', status: 'pending', progress: 0 },
  { id: 'transcribing', label: 'Transcribing', description: 'Converting speech to text (multi-language)', status: 'pending', progress: 0 },
  { id: 'ocr', label: 'Reading Text (OCR)', description: 'Extracting on-screen text from video frames', status: 'pending', progress: 0 },
  { id: 'understanding', label: 'Understanding Content', description: 'AI analyzing and categorizing information', status: 'pending', progress: 0 },
  { id: 'generating_summary', label: 'Generating Summary', description: 'Creating structured summary and insights', status: 'pending', progress: 0 },
  { id: 'saving', label: 'Saving to Knowledge Base', description: 'Storing processed data securely', status: 'pending', progress: 0 },
];

// --- Suggested Search Queries ---
export const SUGGESTED_SEARCHES = [
  'Show food reels',
  'Find AI workshops',
  'Hackathons in Kerala',
  'Recipes with chicken',
  'Cheap headphones',
  'Scholarships for Masters',
  'Budget travel destinations',
  'Free online courses',
];

// --- Suggested Chat Questions ---
export const SUGGESTED_CHAT_QUESTIONS = [
  'Which scholarships expire this month?',
  'Show cafes near me',
  'What reels mention Python?',
  'Find the travel reel I saved last week',
  'Compare headphone prices',
  'What hackathons are coming up?',
];
